version: '3'
services:
  mysqldb:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: 'db_script'
      MYSQL_USER: 'db_script'
      MYSQL_PASSWORD: 'db_script'
      MYSQL_ROOT_PASSWORD: 'db_script'
    ports:
      - '9006:3306'
  cgi:
    image: hypoport/httpd-cgi
    ports:
    - "9080:80"
    volumes:
    - ./cgi/get-the-content:/usr/local/apache2/cgi-bin/get-the-content
  script:
    build: 
      context: ./script
      dockerfile: Dockerfile
    environment:
      MYSQL_DATABASE: 'db_script'
      MYSQL_USER: 'db_script'
      MYSQL_PASSWORD: 'db_script'
      MYQSQL_HOSTNAME: 'mysqldb'
    ports:
    - "9082:80"
    volumes:
    - ./script:/var/www/html
  mvc:
    build: 
      context: ./mvc
      dockerfile: Dockerfile
    environment:
      CONNECTION_STRING: 'Server=mysqldb; Port=3306; Database=db_script; user=db_script; password=db_script;'
    ports:
    - "9083:80"
  spa-api:
    build: 
      context: ./spa/api
      dockerfile: Dockerfile
    environment:
      CONNECTION_STRING: 'Server=mysqldb; Port=3306; Database=db_script; user=db_script; password=db_script;'
    ports:
    - "9084:80"
  spa-fe:
    build: 
      context: ./spa/fe
      dockerfile: Dockerfile
    ports:
    - "9085:80"